//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adminID { get; set; }
        public string adminAdi { get; set; }
        public string adminSoyadi { get; set; }
        public string adminSifre { get; set; }
        public Nullable<int> adminYetki { get; set; }
    
        public virtual YetkiTur YetkiTur { get; set; }
    }
}
