//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonemlikAlinanProje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonemlikAlinanProje()
        {
            this.ProjeIslems = new HashSet<ProjeIslem>();
        }
    
        public int AlinanProjeID { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<int> ogrElmID { get; set; }
        public Nullable<int> donemID { get; set; }
        public Nullable<int> ogrID { get; set; }
    
        public virtual Donemler Donemler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual OgretimElemanlari OgretimElemanlari { get; set; }
        public virtual Projeler Projeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjeIslem> ProjeIslems { get; set; }
    }
}
