//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretimElemanlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgretimElemanlari()
        {
            this.DonemlikAlinanProje = new HashSet<DonemlikAlinanProje>();
            this.OgrenciRaporlaris = new HashSet<OgrenciRaporlari>();
            this.Toplanti = new HashSet<Toplanti>();
            this.OgrenciProjeGonderim = new HashSet<OgrenciProjeGonderim>();
        }
    
        public int SicilNo { get; set; }
        public string ogrElmAd { get; set; }
        public string ogrElmSoyad { get; set; }
        public Nullable<int> ogrElmBolum { get; set; }
        public string ogrElmMail { get; set; }
        public string ogrElmSifre { get; set; }
        public Nullable<int> yetkiTuru { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonemlikAlinanProje> DonemlikAlinanProje { get; set; }
        public virtual YetkiTur YetkiTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciRaporlari> OgrenciRaporlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toplanti> Toplanti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciProjeGonderim> OgrenciProjeGonderim { get; set; }
    }
}
