//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciRaporlari
    {
        public int RaporID { get; set; }
        public Nullable<int> OgrID { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaYolu { get; set; }
        public Nullable<System.DateTime> YuklenmeTarihi { get; set; }
        public Nullable<int> ogrElmID { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual Projeler Projeler { get; set; }
        public virtual OgretimElemanlari OgretimElemanlari { get; set; }
    }
}
