//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeIslem
    {
        public int işlemID { get; set; }
        public Nullable<int> alinanProjeID { get; set; }
        public Nullable<System.DateTime> verilenTarih { get; set; }
        public Nullable<System.DateTime> gorulenTarih { get; set; }
        public Nullable<int> durumID { get; set; }
        public Nullable<int> ogrID { get; set; }
        public string aciklama { get; set; }
        public string projeAdi { get; set; }
        public string projeYorum { get; set; }
        public Nullable<bool> projeOkuma { get; set; }
    
        public virtual DonemlikAlinanProje DonemlikAlinanProje { get; set; }
        public virtual Durum Durum { get; set; }
    }
}
