//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toplanti
    {
        public int ToplantiID { get; set; }
        public Nullable<int> ogrElmID { get; set; }
        public Nullable<System.DateTime> toplantiTarihi { get; set; }
        public string toplantiAciklama { get; set; }
        public string toplantiLinki { get; set; }
        public Nullable<int> ogrID { get; set; }
        public Nullable<bool> tümOgrenciler { get; set; }
    
        public virtual OgretimElemanlari OgretimElemanlari { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
